CVGS/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CVGS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CVGS.Controllers
{
    [Authorize(Roles = "administrators")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<User> userManager;

        // Initializes the controller.
        public RoleController(RoleManager<IdentityRole> roleManager,
                                        UserManager<User> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        // Index: The default action for this controller.
        // Displays a list of roles ordered by name.
        [HttpGet]
        public IActionResult Index()
        {
            var roles = roleManager.Roles;
            return View(roles.OrderBy(m => m.Name));
        }

        //POST CreateRole: Processes a form from the index action, attempting to create a new role.
        [HttpPost]
        public async Task<IActionResult> CreateRole(string roleName)
        {
            if (roleName != null)
                roleName = roleName.Trim();
            if (roleName == null || roleName == "")
            {
                TempData["message"] = "Role Name must not be blank.";
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                IdentityRole role = new IdentityRole { Name = roleName };

                var result = await roleManager.CreateAsync(role);

                if (result.Succeeded)
                {
                    TempData["message"] = $"role added: {roleName}.";
                    return RedirectToAction("Index");
                }
                else if (await roleManager.RoleExistsAsync(roleName))
                {
                    TempData["message"] = $"{roleName} already exists as a role.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = result.Errors.First().Description;
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        //ListUsersInRole: An action that shows a list of all the users in a selected role id. If no role id is passed 
        //as a parameter, user is sent back to the index. Allows the user to add or remove users from the role.
        [HttpGet]
        public async Task<IActionResult> ListUsersInRole(string id)
        {
            ViewBag.roleId = id;

            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                //No role for id
                TempData["message"] = $"Role with id = {id} cannot be found.";
                var roles = roleManager.Roles;
                return View("Index", roles);
            }
            else
            {
                ViewBag.roleName = role.Name;
            }

            var model = new List<UserViewModel>();
            foreach (var user in userManager.Users)
            {
                var userViewModel = new UserViewModel
                {
                    UserId = user.Id,
                    UserName = user.UserName,
                    Email = user.Email
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                    userViewModel.IsInRole = true;
                else
                    userViewModel.IsInRole = false;

                model.Add(userViewModel);
            }

            return View(model.OrderBy(m => m.UserName));
        }

        //CreateUserRole: Processes a request from the ListUsersInRole page, attempting to assign a selected user
        //to a role.
        [HttpPost]
        public async Task<IActionResult> CreateUserRole(string userId, string roleId)
        {

            var user = await userManager.FindByIdAsync(userId);
            var role = await roleManager.FindByIdAsync(roleId);
            IdentityResult result = null;

            result = await userManager.AddToRoleAsync(user, role.Name);
            if (result.Succeeded)
            {
                TempData["message"] = $"{user.UserName} added to {role.Name}.";
            }
            else
            {
                // Error
                TempData["message"] = result.Errors.First().Description;
            }
            return RedirectToAction(actionName: "ListUsersInRole", new { id = role.Id });
        }

        //RemoveUserRole: Processes a request from the ListUsersInRole page, attempting to remove a selected user
        //from a role.
        [HttpGet]
        public async Task<IActionResult> RemoveUserRole(string userId, string roleId)
        {

            var user = await userManager.FindByIdAsync(userId);
            var role = await roleManager.FindByIdAsync(roleId);
            IdentityResult result = null;

            if (User.Identity.Name == user.UserName && role.Name == "administrators")
            {
                TempData["message"] = $"Can not remove current uesr from administrators role.";
                return RedirectToAction(actionName: "ListUsersInRole", new { id = role.Id });
            }
            result = await userManager.RemoveFromRoleAsync(user, role.Name);
            if (result.Succeeded)
            {
                TempData["message"] = $"{user.UserName} removed from {role.Name}.";
            }
            else
            {
                // Error
                TempData["message"] = result.Errors.First().Description;
            }
            return RedirectToAction(actionName: "ListUsersInRole", new { id = role.Id });
        }

        //DeleteRole: Processes a request from the Index page, attempting to delete a role. If the role has no users, it is 
        //deleted instantly. If users are assigned to the role, a confirmation page is displayed, asking if the user is sure if 
        //they want to delete the role.
        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                TempData["message"] = $"Role not found.";
                return RedirectToAction("Index");
            }
            else
            {
                if (role.Name == "administrators")
                {
                    TempData["message"] = $"administrators can not be deleted.";
                    return RedirectToAction("Index");
                }
                var numberOfUsersInRole = await userManager.GetUsersInRoleAsync(role.Name);
                if (numberOfUsersInRole.Count == 0)
                {
                    //If no users, just delete the role.
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        TempData["message"] = $"{role.Name} was deleted.";
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        TempData["message"] = result.Errors.First().Description;
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    ViewBag.roleId = id;
                    ViewBag.roleName = role.Name;

                    var model = new List<UserViewModel>();
                    foreach (var user in userManager.Users)
                    {
                        var userViewModel = new UserViewModel
                        {
                            UserId = user.Id,
                            UserName = user.UserName
                        };

                        if (await userManager.IsInRoleAsync(user, role.Name))
                            userViewModel.IsInRole = true;
                        else
                            userViewModel.IsInRole = false;

                        model.Add(userViewModel);
                    }

                    return View(model);
                }
            }
        }

        //POST DeleteRolePost: Processes a request from the DeleteRole page, confirming the user wants to delete a role
        //that has users assigned to the role.
        [HttpPost]
        public async Task<IActionResult> DeleteRolePost(string id)
        {
            var role = await roleManager.FindByIdAsync(id);
            if (role == null)
            {
                TempData["message"] = $"Role not found.";
                return RedirectToAction("Index");
            }
            else
            {
                if (role.Name == "administrators")
                {
                    TempData["message"] = $"administrators can not be deleted.";
                    return RedirectToAction("Index");
                }
                //If not admin, just delete the role.
                var result = await roleManager.DeleteAsync(role);

                if (result.Succeeded)
                {
                    TempData["message"] = $"{role.Name} was deleted.";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["message"] = result.Errors.First().Description;
                    return RedirectToAction("Index");
                }
            }
        }
    }
}

CVGS/Views/Role/DeleteRole.cshtml
@model IEnumerable<UserViewModel>
@{
    var roleId = ViewBag.roleId;
    var roleName = ViewBag.roleName;
    ViewData["Title"] = $"Confirm delete of Role '{roleName}'";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Role" asp-action="DeleteRolePost" asp-route-id="@roleId" method="post">
    <h4>Users in Role:</h4>
    <ul>
        @foreach (var user in Model)
        {
            @if (user.IsInRole)
            {
                <li>@user.UserName</li>
            }
        }
    </ul>
    <button class="btn btn-danger" type="submit" value="">Delete Confirmed</button>
    <a class="btn btn-secondary" asp-action="Index" asp-controller="CARole">Cancel Delete</a>
</form>

<a asp-action="Index" asp-controller="Role">Return to Role List</a>

CVGS/Views/Role/Index.cshtml
@using Microsoft.AspNetCore.Identity;
@model IEnumerable<IdentityRole>
@{
    ViewData["Title"] = "Current Roles";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Role" asp-action="CreateRole" method="post">
    <label>Create New Role:</label>
    <input type="text" name="roleName" />
    <input type="submit" class="btn btn-primary" value="Create" />
</form>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a asp-action="ListUsersInRole" asp-route-id="@item.Id">Users In Role</a> |
                        @if (item.Name != "administrators")
                        {
                            <a asp-action="DeleteRole" asp-route-id="@item.Id">Delete Role</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

CVGS/Views/Role/ListUsersInRole.cshtml
@model IEnumerable<UserViewModel>
@{
    var roleId = ViewBag.roleId;
    var roleName = ViewBag.roleName;
    ViewData["Title"] = $"Users In Role '{roleName}'";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Role" asp-action="CreateUserRole" asp-route-roleId="@roleId" method="post">
    <label>Users Not in Role:</label>

    <select id="ddlUsersNotInRole" name="userId">
        @foreach (var user in Model)
        {
            @if (!user.IsInRole)
            {
                <option value="@user.UserId">@user.UserName</option>
            }
        }
    </select>
    <input type="submit" class="btn btn-primary" value="Add to Role" />
</form>

@if (Model.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.UserName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                @if (item.IsInRole)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            <a asp-action="RemoveUserRole" asp-route-roleId="@roleId" asp-route-userId="@item.UserId">Remove</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
}

<a asp-action="Index" asp-controller="Role">Return to Role List</a>